<map version="docear 1.1" project="1527A2B3E80A53JZDFS4EGC1POI7LFQEDAON" project_last_home="file:/D:/Dokumente/Promotion/Notizen/Heart" dcr_id="1453749169214_2hlok2xmmurfp24fpsyjr2afd">
<!--To view this file, download Docear - The Academic Literature Suite from http://www.docear.org -->
<node TEXT="Heart" FOLDED="false" ID="ID_990011075" CREATED="1453749169047" MODIFIED="1453824926606">
<hook NAME="AutomaticEdgeColor" COUNTER="1"/>
<hook NAME="MapStyle" zoom="0.494">
    <properties show_note_icons="true" show_icon_for_attributes="true"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node">
<stylenode LOCALIZED_TEXT="styles.predefined" POSITION="right">
<stylenode LOCALIZED_TEXT="default" MAX_WIDTH="600" COLOR="#000000" STYLE="as_parent">
<font NAME="SansSerif" SIZE="10" BOLD="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details"/>
<stylenode LOCALIZED_TEXT="defaultstyle.note"/>
<stylenode LOCALIZED_TEXT="defaultstyle.floating">
<edge STYLE="hide_edge"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" POSITION="right">
<stylenode LOCALIZED_TEXT="styles.topic" COLOR="#18898b" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subtopic" COLOR="#cc3300" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subsubtopic" COLOR="#669900">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.important">
<icon BUILTIN="yes"/>
</stylenode>
<stylenode TEXT="number" STYLE="bubble">
<font ITALIC="true"/>
<cloud COLOR="#ccccff" SHAPE="RECT"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" POSITION="right">
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#000000">
<font SIZE="18"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" COLOR="#0033ff">
<font SIZE="16"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" COLOR="#00b439">
<font SIZE="14"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" COLOR="#990000">
<font SIZE="12"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" COLOR="#111111">
<font SIZE="10"/>
</stylenode>
</stylenode>
</stylenode>
</map_styles>
</hook>
<node TEXT="electrical activity" POSITION="right" ID="ID_1983697933" CREATED="1453749208903" MODIFIED="1453803342967">
<edge COLOR="#ff0000"/>
<node TEXT="Action potential generation" ID="ID_781967274" CREATED="1453749244100" MODIFIED="1453749250174">
<node TEXT="electrical conductance within the heart" ID="ID_129286125" CREATED="1453749251469" MODIFIED="1453751428219"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        AP generated by SA node spreads cell-to-cell across atria
      </li>
      <li>
        some evidence for specialized myocytes that act as conducting pathways (internodal tracts)
      </li>
      <li>
        atria and ventricles are separated by non-conducting tissue
      </li>
      <li>
        =&gt; signal can only travel through the atrioventricular node (AV node)
      </li>
      <li>
        signal reaches ventricle through bundle of His into bundle branches
      </li>
      <li>
        bundle branches divide into Purkinje fibers
      </li>
      <li>
        Purkinje fibers connect to ventricular myocytes
      </li>
      <li>
        =&gt; near synchronous depolarization of ventricular myocytes is permitted

        <ul>
          <li>
            needed to generate pressure efficiently
          </li>
          <li>
            disturbances can lead to arrhythmia
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="cell-to-cell conductance" ID="ID_516381262" CREATED="1453749521096" MODIFIED="1453749757824"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        cells connected by low-resistance gap junctions
      </li>
      <li>
        =&gt; ionic current can flow from one cell to the other
      </li>
      <li>
        generate AP if they are strong enough to depolarize the cell beyond its threshold
      </li>
      <li>
        same process is repeated for next cells
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="conduction velocity of myocytes (atrial and ventricular): 0.5 m/s" STYLE_REF="number" ID="ID_1493071851" CREATED="1453749801100" MODIFIED="1453751211875"/>
</node>
<node TEXT="atrioventricular node (AV node)" ID="ID_1379115310" CREATED="1453750385788" MODIFIED="1453750527648"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        highly specialized conducting tissue (cardiac, not neural)
      </li>
      <li>
        slows input conduction velocity
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="conduction velocity of AV node: 0.005 m/s" STYLE_REF="number" ID="ID_526706892" CREATED="1453750538009" MODIFIED="1453750580738"/>
<node TEXT="delay between atria and ventricles" ID="ID_1520937677" CREATED="1453750685121" MODIFIED="1453750948989"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        atria have to be emptied before ventricular contraction can begin
      </li>
      <li>
        limits frequency of impulses generated and thus frequency of ventricular contractions
      </li>
      <li>
        protects from atrial flutter reaching the ventricles
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
<node TEXT="conduction velocity of bundle branches: 2 m/s" STYLE_REF="number" ID="ID_961904607" CREATED="1453751081635" MODIFIED="1453751128758"/>
<node TEXT="conduction velocity of Purkinje fibers: 4 m/s" STYLE_REF="number" ID="ID_528746409" CREATED="1453751107624" MODIFIED="1453751128739"/>
<node TEXT="regulation of conduction velocity" ID="ID_1145644695" CREATED="1453751453435" MODIFIED="1453752476723"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <table border="0" style="width: 80%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 0; border-right-width: 0; border-bottom-width: 0; border-left-width: 0">
      <tr>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            <b>increasing factors </b>
          </p>
        </td>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            <b>decreasing factors</b>
          </p>
        </td>
      </tr>
      <tr>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            sympathetic stimulation
          </p>
        </td>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            parasympathetic stimulation
          </p>
        </td>
      </tr>
      <tr>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            M_2 antagonists
          </p>
        </td>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            M_2 agonists
          </p>
        </td>
      </tr>
      <tr>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            beta-adrenoreceptor agonists
          </p>
        </td>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            beta-blocker
          </p>
        </td>
      </tr>
      <tr>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            circulating catecholamines
          </p>
        </td>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            ischemia/hypoxia
          </p>
        </td>
      </tr>
      <tr>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            hyperthyroidism
          </p>
        </td>
        <td valign="top" style="width: 50%; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-width: 1; border-right-width: 1; border-bottom-width: 1; border-left-width: 1">
          <p style="margin-top: 1; margin-right: 1; margin-bottom: 1; margin-left: 1">
            sodium and calcium channel blockers
          </p>
        </td>
      </tr>
    </table>
  </body>
</html>
</richcontent>
<node TEXT="AV nodal tissue" ID="ID_958157018" CREATED="1453751857277" MODIFIED="1453752435271"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        depolarization rate determined by slow inward calcium currents
      </li>
    </ul>
  </body>
</html>
</richcontent>
</node>
<node TEXT="other myocytes" ID="ID_264710839" CREATED="1453751865957" MODIFIED="1453751956062"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        depolarization rate determined by fast sodium channels
      </li>
    </ul>
  </body>
</html>
</richcontent>
</node>
<node TEXT="sympathetic influence" ID="ID_1274463151" CREATED="1453752563623" MODIFIED="1453756640664"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        increases conduction velocity via norepinephrine binding to beta1-adrenoreceptors
      </li>
    </ul>
  </body>
</html>
</richcontent>
</node>
<node TEXT="parasympathetic influence" ID="ID_286378311" CREATED="1453752636163" MODIFIED="1453756631585"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        decreases conduction velocity via the action of ACh on M_2 receptors
      </li>
      <li>
        most prominent at AV node (high degree of vagal innervation)
      </li>
    </ul>
  </body>
</html>
</richcontent>
</node>
</node>
<node TEXT="abnormal conduction" ID="ID_391630527" CREATED="1453756710209" MODIFIED="1453756714421">
<node TEXT="complete block of AV node" ID="ID_247641605" CREATED="1453756963580" MODIFIED="1453757300783"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        impulses cannot travel from atria to ventricles
      </li>
      <li>
        latent pacemakers in the ventricular conduction system take over
      </li>
      <li>
        but with reduced firing rate =&gt; ventricular bradycardia
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="block of one of the bundle branches" ID="ID_650193171" CREATED="1453757111123" MODIFIED="1453757292179"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        ventricular depolarization still occurs but pathways are altered
      </li>
      <li>
        =&gt; activation delay and reduced contraction efficiency
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="ectopic beat within ventricle" ID="ID_373996586" CREATED="1453757198694" MODIFIED="1453757280488"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        can alter pathway of depolarization, such that it has to rely on slow cell-to-cell conductance
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
<node TEXT="reentry" ID="ID_647799589" CREATED="1453796899976" MODIFIED="1453797394451"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        reason: conducting pathway stimulated prematurely
      </li>
      <li>
        can occur at any &quot;loop&quot; in conduction system (e.g. different branches of Purkinje fibers)
      </li>
      <li>
        part of one branch may have a unidirectional block
      </li>
      <li>
        normal behavior: signals from two sides cancel each other out
      </li>
      <li>
        with block: signal from one side can &quot;loop around&quot; to the other side

        <ul>
          <li>
            if loop cycle period is larger than refractory period
          </li>
        </ul>
      </li>
      <li>
        can lead to rapid cyclical activations =&gt; tachycardia
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="mechanisms affecting reentry" ID="ID_928411401" CREATED="1453797590348" MODIFIED="1453797847680"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        alteration of conduction velocity or&#160;tissue refractoriness can create or abolish reenty
      </li>
      <li>
        =&gt; reentry can be paroxysmal (sudden appearance and disappearance) due to normal variances
      </li>
      <li>
        changes can come from autonomic system
      </li>
      <li>
        or antiarrhythmic drugs
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="global reentry" ID="ID_405737273" CREATED="1453797854058" MODIFIED="1453885868301" MOVED="1453801680341"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        between ventricle and atria
      </li>
      <li>
        involve accessory conduction pathways (e.g. bundle of Kent)
      </li>
      <li>
        results in supraventricular tachyarrhythmias (e. g. Wolff-Parkinson-White syndrome)
      </li>
    </ul>
  </body>
</html>

</richcontent>
<hook URI="project://1527A2B3E80A53JZDFS4EGC1POI7LFQEDAON/images/WPW.jpeg" SIZE="1.0" NAME="ExternalObject"/>
</node>
<node TEXT="local reentry" ID="ID_125187257" CREATED="1453797862154" MODIFIED="1453798235003"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        within small region of ventricle or atrium
      </li>
      <li>
        lead to ventricular or atrial tachyarrhythmias
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
<node TEXT="accessory conduction pathways" ID="ID_833183212" CREATED="1453798024201" MODIFIED="1453798099891"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        e.g. bundle of Kent
      </li>
      <li>
        alternative routes to the AV node
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
</node>
<node TEXT="the electrocardiogram (ECG)" ID="ID_1233625129" CREATED="1453803346835" MODIFIED="1453817638875">
<hook URI="project://1527A2B3E80A53JZDFS4EGC1POI7LFQEDAON/images/SinusRhythmLabels.svg" SIZE="0.543971" NAME="ExternalObject"/>
<richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        electrical currents of depolarization and repolarization are conducted by tissue surrounding the heart
      </li>
      <li>
        ECG = measurement of these currents by array of electrodes placed on specific locations on the body
      </li>
      <li>
        measures voltage changes from baseline
      </li>
      <li>
        generally recorded on paper at speed of 25 mm/s and 1 mV/cm
      </li>
      <li>
        dependent on several conditions

        <ul>
          <li>
            location of recording electrodes
          </li>
          <li>
            conduction pathways
          </li>
          <li>
            changes in muscle mass
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="P wave" ID="ID_368120032" CREATED="1453804283725" MODIFIED="1453809515931"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        depolarization spreading from SA node to atria
      </li>
      <li>
        atrial repolarization is not visible because it is masked by ventricular depolarization
      </li>
      <li>
        brief isoelectric period after P wave: atrial cells depolarized, impulse travels through AV node
      </li>
      <li>
        PR-Interval = time between onset of atrial and ventricular depolarization

        <ul>
          <li>
            &gt; 0.2 s =&gt; probably conduction defect (AV block)
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="duration of P wave: 0.08 to 0.1 s" STYLE_REF="number" ID="ID_1060722589" CREATED="1453804570418" MODIFIED="1453804604897"/>
<node TEXT="PR-Interval: 0.12 to 0.2 s" STYLE_REF="number" ID="ID_1031893533" CREATED="1453804622747" MODIFIED="1453805265488"/>
</node>
<node TEXT="QRS complex" ID="ID_611770040" CREATED="1453804774105" MODIFIED="1453805389490"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        represents ventricular depolarization
      </li>
      <li>
        duration &gt; 0.1 s =&gt; conduction within ventricles is impaired

        <ul>
          <li>
            defects (e.g. bundle branch blocks)
          </li>
          <li>
            aberrant conduction
          </li>
          <li>
            ectopic ventricular pacemaker (uses slower pathways)
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="duration of QRS complex: 0.06 to 0.1 s" STYLE_REF="number" ID="ID_178918245" CREATED="1453805020664" MODIFIED="1453805409118"/>
</node>
<node TEXT="ST segment" ID="ID_441272713" CREATED="1453805484565" MODIFIED="1453805615369"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        entire ventricle depolarized
      </li>
      <li>
        roughly corresponds to plateau phase of ventricular AP
      </li>
      <li>
        depressed or elevated ST segment indicates nonuniform membrane potentials

        <ul>
          <li>
            can be a sign of ventricular ischemia
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="T wave" ID="ID_1003368647" CREATED="1453805667411" MODIFIED="1453805790381"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        represents ventricular repolarization
      </li>
      <li>
        longer than depolarization
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="QT interval" ID="ID_1527911318" CREATED="1453805801626" MODIFIED="1453806058447"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        rough estimate for duration of ventricular AP
      </li>
      <li>
        depends on heart rate

        <ul>
          <li>
            higher rate =&gt; shorter AP =&gt; shorter QT-interval
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="QTc-interval" ID="ID_869121358" CREATED="1453808328624" MODIFIED="1453808657739"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <p>
      QT interval divided by RR interval
    </p>
    <p>
      allows to assess QT interval independent of heart rate
    </p>
    <p>
      can help to detect susceptibility to some arrhythmias
    </p>
  </body>
</html>

</richcontent>
<node TEXT="corrected QT-interval (QTc): &lt; 0.44 s" STYLE_REF="number" ID="ID_1057513584" CREATED="1453808524206" MODIFIED="1453808552960"/>
</node>
<node TEXT="QT interval: 0.2 to 0.4 s" STYLE_REF="number" ID="ID_1797091001" CREATED="1453808496335" MODIFIED="1453808520145"/>
</node>
<node TEXT="normal and abnormal cardiac rhythms" ID="ID_169831749" CREATED="1453809053880" MODIFIED="1453814677972">
<hook URI="project://1527A2B3E80A53JZDFS4EGC1POI7LFQEDAON/images/2024_Cardiac_Arrhythmias.jpg" SIZE="0.3" NAME="ExternalObject"/>
<node TEXT="rhythm strip" ID="ID_1201376708" CREATED="1453809247722" MODIFIED="1453809498193"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        records P wave and QRS complex frequency
      </li>
      <li>
        usually generated from a single ECG lead (often lead II)
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="sinus rhythm" ID="ID_729396084" CREATED="1453809317985" MODIFIED="1453809710990"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        normal condition of the heart
      </li>
      <li>
        one-to-one correspondence between P wave and QRS complex
      </li>
      <li>
        ventricular depolarization triggered by atrial depolarization
      </li>
      <li>
        &quot;sinus rhythm&quot; because SA node is controlling the rhythm
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="sinus rhythm: 60 to 100 beats/min" STYLE_REF="number" ID="ID_1880460482" CREATED="1453809716383" MODIFIED="1453809747504"/>
<node TEXT="sinus bradycardia" ID="ID_1227711925" CREATED="1453809880413" MODIFIED="1453810189523"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        lower heart rate than normal ( &lt; 60 bpm)
      </li>
      <li>
        normal resting rate can be below 60 bpm for some people (e.g. athletes)
      </li>
      <li>
        may also result from depressed SA nodal function
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="sinus tachycardia" ID="ID_1898913630" CREATED="1453810195292" MODIFIED="1453810521299"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        higher heart rate than normal
      </li>
      <li>
        abnormal at rest, but normal during exercise or when a person becomes excited
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="tachycardia sinus rhythm: 100 to 180 beats/min" STYLE_REF="number" ID="ID_1642544184" CREATED="1453810527529" MODIFIED="1453810580887"/>
</node>
</node>
<node TEXT="atrial flutter" ID="ID_44090471" CREATED="1453810808503" MODIFIED="1453811519170"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        atrial rate is so high that not all impulses are conducted through AV node
      </li>
      <li>
        =&gt; ventricular rate may be less than half of atrial rate
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="atrial fibrillation" ID="ID_487644625" CREATED="1453811522777" MODIFIED="1453811747382"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        SA node does not trigger atrial depolarization
      </li>
      <li>
        instead depolarization from many sites throughout the atria
      </li>
      <li>
        =&gt; uncoordinated low-voltage high-frequency depolarizations with no discernable P waves
      </li>
      <li>
        ventricular rate irregular and rapid
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="AV block" ID="ID_445886087" CREATED="1453811755703" MODIFIED="1453812957734"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        depressed impulse conduction
      </li>
      <li>
        atrial rate is normal, but not every atrial depolarization followed by a ventricular depolarization
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="first-degree AV block" ID="ID_728812729" CREATED="1453813445371" MODIFIED="1453813578640" MOVED="1453813473759"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        one-to-one correspondence remains, but PR interval is &gt; 0.2 s
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="second-degree AV block" ID="ID_239997709" CREATED="1453812966751" MODIFIED="1453813441834"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        two or three P waves preceding each QRS complex
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="third-degree AV block" ID="ID_987178183" CREATED="1453813584554" MODIFIED="1453814181680"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        no atrial depolarizations are conducted
      </li>
      <li>
        complete disscociation between P waves and QRS complexes
      </li>
      <li>
        ventricular depolarization still happens due to secondary latent pacemaker site

        <ul>
          <li>
            within AV junction
          </li>
          <li>
            or ectopic foci within ventricles
          </li>
        </ul>
      </li>
      <li>
        slow ventricular rate (&#160;&lt; 40 beats / min)

        <ul>
          <li>
            due to slower firing rate of secondary, latent pacemakers
          </li>
        </ul>
      </li>
      <li>
        if ectopic foci are in ventricles, QRS has abnormal shape and is wider
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="firing rate of pacemakers in AV node and bundle of His: 50 to 60 beats/min" STYLE_REF="number" ID="ID_540539976" CREATED="1453814151406" MODIFIED="1453814265987"/>
<node TEXT="firing rate of pacemakers in Purkinje system: 30 to 40 beats/min" STYLE_REF="number" ID="ID_891810171" CREATED="1453814211166" MODIFIED="1453814266004"/>
</node>
</node>
<node TEXT="ventricular tachycardia" ID="ID_685521884" CREATED="1453814930337" MODIFIED="1453815364402"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        ventricular rate &gt; atrial rate
      </li>
      <li>
        most common cause: reentry circuits

        <ul>
          <li>
            due to abnormal impulse conduction
          </li>
          <li>
            or rapidly firing ectopic pacemaker sites within the ventricles (caused by afterdepolarizations)
          </li>
        </ul>
      </li>
      <li>
        dissociation between atrial and ventricular rates
      </li>
      <li>
        impars ventricular filling
      </li>
      <li>
        reduces stroke volume
      </li>
      <li>
        can lead to ventricular fibrillation
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="heart rate during ventricular tachycardia: 100 to 200 beats/min" STYLE_REF="number" ID="ID_1566656024" CREATED="1453815375629" MODIFIED="1453815490105"/>
<node TEXT="ventricular flutter" ID="ID_723432431" CREATED="1453815400803" MODIFIED="1453815480936"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        more severe form of ventricular tachycardia (higher rates)
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="heart rate during ventricular flutter: &gt; 200 beats/min" STYLE_REF="number" ID="ID_1427813205" CREATED="1453815425179" MODIFIED="1453815490117"/>
</node>
</node>
<node TEXT="ventricular fibrillation" ID="ID_1136441022" CREATED="1453815526778" MODIFIED="1453815693606"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        rapid, low-voltage, uncoordinated depolarizations
      </li>
      <li>
        no discernable QRS complex
      </li>
      <li>
        cardiac output goes to zero =&gt; lethal
      </li>
      <li>
        can sometimes be reverted to sinus rhythm by electrical defibrillation

        <ul>
          <li>
            applying strong but brief electrical currents to the heart
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="premature depolarization" ID="ID_1973767872" CREATED="1453815879560" MODIFIED="1453816025051"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        within atria or ventricles
      </li>
      <li>
        caused by ectopic pacemaker sites
      </li>
      <li>
        appear as extra (early) P waves or QRS complexes
      </li>
      <li>
        often abnormally shaped, because ectopic pacemakers do not follow normal pathways
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
<node TEXT="principles and rules of interpretation" ID="ID_824768726" CREATED="1453817471092" MODIFIED="1453817529918">
<node TEXT="electrical vectors" ID="ID_1294053332" CREATED="1453817531556" MODIFIED="1453818668643"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        depolarization is conducted through the heart along several &quot;waves&quot;
      </li>
      <li>
        waves can be seen as vectors of electrical potential
      </li>
      <li>
        the mean of all these vectors is recorded by the ECG leads
      </li>
      <li>
        depending on the location of the lead and the orientation of the mean electrical vector the signal may be strong in one lead but weak in others
      </li>
      <li>
        =&gt; shape of QRS depends on placement of electrodes
      </li>
    </ul>
    <img src="images/QRS vectors animation.gif" width="350" height="281"/>
  </body>
</html>

</richcontent>
<node TEXT="interpretation rules" ID="ID_1632142591" CREATED="1453818738604" MODIFIED="1453818979582"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        wave of depolarization traveling towards positive electrode =&gt; positive deflection in ECG curve
      </li>
      <li>
        wave of repolarization traveling towards positive electrode =&gt; negative deflection in ECG
      </li>
      <li>
        wave of de-/re-polarization perpendicular to electrode axis =&gt; no deflection
      </li>
      <li>
        amplitude of measured potentials depends on orientation of electrode relative to mean electrical vector
      </li>
      <li>
        voltage amplitude ist directly related to mass of tissue undergoing de-/re-polarization
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
<node TEXT="electrode placement" ID="ID_518904101" CREATED="1453819476175" MODIFIED="1453821647457"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        conventionally, 10 electrodes

        <ul>
          <li>
            right/left arm
          </li>
          <li>
            right/left leg
          </li>
          <li>
            6 electrodes at defined locations on the chest
          </li>
        </ul>
      </li>
      <li>
        record 3 basic types of leads

        <ul>
          <li>
            standard limb leads
          </li>
          <li>
            augmented limb leads
          </li>
          <li>
            chest leads
          </li>
        </ul>
      </li>
      <li>
        electrode leads connected to device that measures potential differences between selected electrodes
      </li>
      <li>
        =&gt; characteristic ECG tracing
      </li>
    </ul>
  </body>
</html>

</richcontent>
<hook URI="project://1527A2B3E80A53JZDFS4EGC1POI7LFQEDAON/images/2021_ECG_Placement_of_Electrodes.jpg" SIZE="0.5612722" NAME="ExternalObject"/>
<node TEXT="bipolar leads" ID="ID_95963738" CREATED="1453819744956" MODIFIED="1453819806080"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        limb leads
      </li>
      <li>
        single pair of positive and negative electrodes
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="unipolar leads" ID="ID_621842583" CREATED="1453819808611" MODIFIED="1453819870167"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        augmented and chest leads
      </li>
      <li>
        single positive electrode
      </li>
      <li>
        other electrodes coupled together electrically as common negative electrode
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="ECG limb leads" ID="ID_1079329286" CREATED="1453819942171" MODIFIED="1453823157887"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        6 leads
      </li>
      <li>
        spanning a single plane (frontal)
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="standard limb leads" ID="ID_406103698" CREATED="1453819969107" MODIFIED="1453820670217"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        placement: origin or end of limb (does not matter)
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="lead I" ID="ID_585076728" CREATED="1453820035323" MODIFIED="1453820586069">
<attribute_layout NAME_WIDTH="112" VALUE_WIDTH="102"/>
<richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <p>
      positive: right arm
    </p>
    <p>
      negative: left arm
    </p>
  </body>
</html>

</richcontent>
<hook NAME="FirstGroupNode"/>
</node>
<node TEXT="lead II" ID="ID_162158890" CREATED="1453820041122" MODIFIED="1453820494843"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <p>
      positive: left leg
    </p>
    <p>
      negative: right arm
    </p>
  </body>
</html>

</richcontent>
</node>
<node TEXT="lead III" ID="ID_28165349" CREATED="1453820051003" MODIFIED="1453820530754"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <p>
      positive: left leg
    </p>
    <p>
      negative: left arm
    </p>
  </body>
</html>

</richcontent>
</node>
<node TEXT="Einthoven Triangle" ID="ID_604741638" CREATED="1453820586061" MODIFIED="1453820593736">
<hook NAME="SummaryNode"/>
</node>
</node>
<node TEXT="augmented limb leads" ID="ID_876322401" CREATED="1453819973947" MODIFIED="1453822115688"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        one positive electrode at corresponding limbs
      </li>
      <li>
        compared to other 3 limb electrodes
      </li>
      <li>
        in practice, same electrodes used as for lead I, II, and II
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="aV_L (left arm)" ID="ID_1537343700" CREATED="1453821907414" MODIFIED="1453821923622"/>
<node TEXT="aV_R (right arm)" ID="ID_1817323573" CREATED="1453821926501" MODIFIED="1453821940902"/>
<node TEXT="aV_F (left leg, &quot;F&quot; stands for &quot;foot&quot;)" ID="ID_856634" CREATED="1453821947541" MODIFIED="1453821970806"/>
</node>
<node TEXT="(hex)axial reference system" ID="ID_1966919014" CREATED="1453821707671" MODIFIED="1453821799884">
<hook URI="project://1527A2B3E80A53JZDFS4EGC1POI7LFQEDAON/images/Hexaxial_reference_system.svg" SIZE="0.8344923" NAME="ExternalObject"/>
</node>
<node TEXT="determining mean electrical axis" ID="ID_1649644170" CREATED="1453822360682" MODIFIED="1453822798941"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        mean electrical axis is perpendicular to lead axis with smallest net QRS amplitude

        <ul>
          <li>
            net amplitude = positive minus negative deflection voltage
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="axis deviations" ID="ID_1822000664" CREATED="1453822801399" MODIFIED="1453822957722"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        deviations of normal range can be important

        <ul>
          <li>
            &lt; -30&#176; =&gt; left axis deviation
          </li>
          <li>
            &gt; 90&#176; =&gt; right axis deviation
          </li>
        </ul>
      </li>
      <li>
        different reasons possible

        <ul>
          <li>
            can occur because of physical position of the heart within the chest
          </li>
          <li>
            or changes in sequence of ventricular activation (conduction defects)
          </li>
          <li>
            can occur if ventricular regions are incapable of being activated (infarct)
          </li>
          <li>
            ventricular hypertrophy
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="normal range for mean electrical axis orientation: -30&#xb0; to + 90&#xb0;" STYLE_REF="number" ID="ID_1803531142" CREATED="1453824680330" MODIFIED="1453824717080"/>
</node>
</node>
<node TEXT="ECG chest leads" ID="ID_727254549" CREATED="1453823048837" MODIFIED="1453823451838"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        span a horizontal plane perpendicular to the limb leads
      </li>
      <li>
        right arm, left arm and left leg electrodes used as combined negative electrode
      </li>
      <li>
        named V1 (front) to V6 (side)
      </li>
      <li>
        normal activation:

        <ul>
          <li>
            V1 net negative
          </li>
          <li>
            V6 net positive
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
</node>
<node TEXT="changes during cardiac ischemia" ID="ID_1785455792" CREATED="1453823693169" MODIFIED="1453824656332"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        ECG is key tool for diagnosing myocardial ischemia and infarction
      </li>
      <li>
        12-lead ECG can identify extent location and progress of damage following ischemic injury
      </li>
    </ul>
  </body>
</html>

</richcontent>
<node TEXT="myocardial infarction" ID="ID_1671739996" CREATED="1453824080262" MODIFIED="1453824146736"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        some types alter conduction
      </li>
      <li>
        =&gt; exaggerated Q waves in specific leads
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="ischemia" ID="ID_1197253650" CREATED="1453824149189" MODIFIED="1453824157351">
<node TEXT="damaged conduction pathways" ID="ID_1381698706" CREATED="1453824158846" MODIFIED="1453824194097"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        results in arrhythmia
      </li>
      <li>
        or changes in QRS shape
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="injury currents" ID="ID_500260182" CREATED="1453824196645" MODIFIED="1453824233484"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        from depolarized ischemic regions to normal regions
      </li>
      <li>
        =&gt; isoelectric portion of ECG is shifted
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
<node TEXT="tissue hypoxia" ID="ID_1208653136" CREATED="1453824246269" MODIFIED="1453824646771"><richcontent TYPE="DETAILS">

<html>
  <head>
    
  </head>
  <body>
    <ul>
      <li>
        leads to membrane depolarization
      </li>
      <li>
        ATP levels decline
      </li>
      <li>
        =&gt; net loss of K+

        <ul>
          <li>
            leaks out through K_ATP channels (normally inhibited by ATP)
          </li>
          <li>
            decreased activity of Na+/K+-ATPAse pump
          </li>
        </ul>
      </li>
      <li>
        increased extracellular K+, decreased intracellular K+
      </li>
      <li>
        =&gt; membrane depolarization
      </li>
      <li>
        =&gt; inactivation of fast sodium channels
      </li>
      <li>
        =&gt; AP upstroke velocity is decreased
      </li>
      <li>
        =&gt; reduced conduction velocity
      </li>
      <li>
        =&gt; reentry currents and tachycardia
      </li>
      <li>
        pacemaker activity is altered
      </li>
      <li>
        latent pacemakers may become active

        <ul>
          <li>
            =&gt; changes in rhythm and ectopic beats
          </li>
        </ul>
      </li>
      <li>
        intracellular calcium accumulates

        <ul>
          <li>
            =&gt; afterdepolarizations and tachycardia
          </li>
        </ul>
      </li>
    </ul>
  </body>
</html>

</richcontent>
</node>
</node>
</node>
</node>
</node>
</node>
</map>
